name: Deploy to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger webhook
        run: |
          curl -X POST http://95.217.234.39:9000/deploy
